### ISSUE TITLE
Please publish crate

### ISSUE THREAD

**Issue by tv42** [rkyv/rkyv_util#6]
I learned about rkyv_util from https://github.com/rkyv/rkyv/issues/501#issuecomment-2282904835 and immediately went to https://docs.rs/rkyv_util -- nothing there, as the crate isn't published. Now I ended up with a git import in my Cargo.toml.

I don't see a reason why this crate wouldn't be published. It's structured as a library, not a copy-paste example, and so on.

Could someone publish the crate, please?

**Comment by djkoloski** [comment]
The current state of the repo has been published as rkyv_util 0.1.0-alpha.1.
